### ISSUE TITLE
Two-way binding does not woork after adding scope to the directive

### ISSUE THREAD

**Issue by venugopalkathavate** [eee-c/angular-bind-polymer#9] opened 2014-12-19 09:13 UTC
I have added scope to the directive like below.

```
angular.module('angularBindPolymer', []).
directive('bindPolymer', function() {
  return {
    restrict: 'A',
    scope: {change: "="}, // Scope added here
    link: function(scope, element, attrs) {
        .........
    }
}
```
After I added the scope, the two way bind stopped working. If I remove scope then everything is back to normal.

**Comment by eee-c** [comment] 2015-01-07 03:34
If possible, can you provide a PR that reproduces this situation? You can replace `index.html` and `test/x-double.html` with something that demonstrates the problem and I can use that to better investigate.

**Comment by venugopalkathavate** [comment] 2015-01-07 06:26
I have updated the angular_bind_polymer.js file. Now you can reproduce the issue.

**Comment by venugopalkathavate** [comment] 2015-01-07 06:28
Since adding scope to directive will limit it to the local directive the parent scope is not getting updated. For now i am trying to update the parent scope. Not sure if that is the correct way to do it.

**Comment by JWGmeligMeyling** [comment] 2015-03-01 13:43
This is how scopes for a directive behave. The implementation of the `bind-polymer` directive is such that it requires to be in the current scope. I'm not sure what you're trying to achieve but have a look at my comment in your PR: https://github.com/eee-c/angular-bind-polymer/pull/11#discussion_r25566801 . I think this is not a bug and can be closed.

**Comment by eee-c** [comment] 2015-03-03 05:07
Thanks for the second set of eyes @JWGmeligMeyling. Closing this issue.

**Closed by eee-c** 2015-03-03 05:07 UTC
Labels: bug
